dist: xenial
language: python
python:
  - "2.7"
  - "3.6"

install:
  - pip install tox-travis

script:
  - tox


# The following section deploys to pypi when a version tag is applied to master, see https://docs.travis-ci.com/user/deployment/pypi/
credentials:
  - &pypi
    provider: pypi
    user: CBampis
    password:
      secure: "VWltwDtLglGIzANTRdnc97GCDEzTDgQLBgOSJIWhYTUJ3baE/tYFO9KfhRK5r4QsPjeKcxMuhMvlxR1BXGej9/mAEMT/AC20E4P/nxjc6DV6pAYeqya8MQm69mllXwNHvmjzdbAVGK6glb+OkPsHxtCDNqimOXJ33nEcK3M3/jer7b7McVTQB5jAKAASf9gBEW6t4SURhrMsStM1GVq77TB/S6Hnfv1XqnSD6e5xNJ76ayN1q9IESECf/RtHDSxR+y6BOelbS2G1WbJREj08VmsIgBc52CPRgKNmiqBelM5y/qBRSL+elhpxtQJDJWl8oNqxxUVn6bOTgVUr/CvUZ0tGYciZJ1Ee6uoC/3J8KgX5dW3Rli73msReSyluOZn1zYEm26FYn3OdPyDETUcKg3y8UBmKfnZ5FEF1L37M3cV9drX00+AH3Kz0JqVz4tzY3Dtq3zZIegRGM594vQ76wfp9FrFgph4mwJyxaTDXjVvz2QRQE84Osr2G9pgj+KWTE7yFGJvzxejYJ4vH2uxa41ZAIkCBs8pmSR2ZjAI8FbLSDUrrwLl2cfAJtVqYhQ0x0bzN0wUL+pZ6qMF3J8Cz0/Xm4+hv7L3rCIa4kUrZCrd2wPjT9bMH+IITfiTOU9AGl1MnbiBX5NeKA4jDT9zSzwR0jt49U0uh3xfhbwBo1+g="

deploy:
  - <<: *pypi
    on:
      # Publish source tarball and wheel with 3.6
      python: 3.6
      repo: Netflix/sureal
      branch: master
      tags: true
    distributions: "sdist bdist_wheel"
  - <<: *pypi
    on:
      # Publish wheel only with 2.7
      python: 2.7
      repo: Netflix/sureal
      branch: master
      tags: true
    distributions: "bdist_wheel"
