dist: xenial
language: python
python:
  - "2.7"
  - "3.6"

install:
  - pip install tox-travis

script:
  - tox


# The following section deploys to pypi when a version tag is applied to master, see https://docs.travis-ci.com/user/deployment/pypi/
credentials:
  - &pypi
    provider: pypi
    user: CBampis
    password:
      secure: "to be filled in"

deploy:
  - <<: *pypi
    on:
      # Publish source tarball and wheel with 3.6
      python: 3.6
      repo: Netflix/sureal
      branch: master
      tags: true
    distributions: "sdist bdist_wheel"
  - <<: *pypi
    on:
      # Publish wheel only with 2.7
      python: 2.7
      repo: Netflix/sureal
      branch: master
      tags: true
    distributions: "bdist_wheel"
