dist: xenial
language: python
python:
  - "2.7"
  - "3.6"

install:
  - pip install tox-travis

script:
  - tox


# The following section deploys to pypi when a version tag is applied to master, see https://docs.travis-ci.com/user/deployment/pypi/
deploy:
  - provider: pypi
    user: CBampis
    password:
      secure: "to be filled in"
    distributions: "sdist bdist_wheel --universal"
    on:
      branch: master
      python: 3.6
      repo: Netflix/sureal
      tags: true
